image: mukn/glow:latest

# NB: Until I implement remote merge-base detection, this parameter is
# the maximum allowed distance to the reference branch (e.g. master)
variables:
  GIT_DEPTH: 50

build:
  stage: build
  before_script:
    - ./scripts/ci.ss before-build
  script:
    - ./scripts/ci.ss build
  after_script:
    - ./scripts/ci.ss after-build


test:
  stage: test
  before_script:
    - ./scripts/ci.ss before-test
  script:
    - ./scripts/ci.ss test
  after_script:
    - ./scripts/ci.ss after-test
  artifacts:
    when: always
    paths:
      - ./run/*
