#!/bin/sh
# This script starts a Gerbil interpreter with all of Glow loaded,
# so you can interact with it at the REPL.
# You can use this file as your M-x run-scheme interpreter
# by putting a line such as the following one in your .emacs
# then using e.g. gerbil-mode:
# (setq scheme-program-name "/home/fricfrac/src/fricfrac/gerbil/my-gxi")

this=$0
here=$(dirname "$this")

. "$here/env.sh"

case "${1-}" in
    --swank) swank="-e (spawn/name'swank\`,start-swank)" ; shift ;;
    *) swank= ;;
esac
if [ $# = 0 ] ; then
    interaction="$GERBIL_HOME/lib/init.ss -"
fi
exec gxi "${here}/all-glow.ss" $swank $interaction "$@"
