#!/bin/sh -e
## Easy Installation script for Glow implementers. See https://glow-lang.org
## This script is for people who intend to modify the Glow language itself,
## its compiler and its runtime.

{ # Prevent execution if this script was only partially downloaded

# 0. Small prelude
panic() {
    echo "$0:" "$@" >&2
    exit 1
}
umask 0022

require_util() {
    command -v "$1" > /dev/null 2>&1 ||
        panic "You do not have '$1' installed, which I need $2"
}

# 1. Make sure Nix is installed, if not installed yet.
require_util curl "to download nix-env"
if ! command -v nix-env > /dev/null 2>&1 ; then
    echo "Installing Nix..."
    curl -L https://nixos.org/nix/install > nix-install.tmp
    sh nix-install.tmp --daemon
    rm nix-install.tmp
fi

# 2. Install Glow, and matching versions of a few other things along with it,
# from the very same version of nixpkgs used by MuKn.
# This ensures that the build is deterministic:
# if it builds for us, it will build identically for you.
echo "Using Nix to install Glow, and with it gerbil, geth, solc, racket..."
nix-env -f https://github.com/fare-patches/nixpkgs/archive/fare.tar.gz -iA \
        glow-lang gerbil-unstable go-ethereum solc racket
# NB: We use racket's scribble for part of our documentation

# 3. Install nix-thunk. See https://github.com/obsidiansystems/nix-thunk
# You will need to use nix-thunk if you build the nix way and need to modify a dependency.
echo "Using Nix to install nix-thunk"
nix-env -f https://github.com/obsidiansystems/nix-thunk/archive/master.tar.gz -iA command

# 4. Download source code so you can modify it.
# This command creates a checkout in the current directory.
# You can move it to a different place.
# If you also need to modify a library that Glow depends on, use nix-thunk as above,
# and/or clone the repository for the dependency in the parent directory, and configure,
# as explained in INSTALL.md.
echo "Checking out the Glow repository"
git clone https://gitlab.com/mukn/glow.git

} # End of wrapping
