name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build_job:
    runs-on: ubuntu-latest
    container: mukn/glow:devel
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - run: ./scripts/ci.ss before-build
      - run: ./scripts/ci.ss build
      - if: ${{ github.event_name == 'push' }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: ./scripts/ci.ss after-build
