name: default

on: [push, pull_request]

defaults:
  run:
    shell: /bin/sh

jobs:
  build_job:
    runs-on: ubuntu-latest
    container: mukn/glow:devel
    defaults:
      run:
        shell: /bin/sh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ./scripts/ci.ss before-build
      - run: ./scripts/ci.ss build
      - if: ${{ github.event_name == 'push' }}
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: ./scripts/ci.ss after-build

  test_job:
    runs-on: ubuntu-latest
    container: mukn/glow:devel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ./scripts/ci.ss before-test
      - run: ./scripts/ci.ss test
      - run: ./scripts/ci.ss after-test
