name: default

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build_test_job:
    runs-on: ubuntu-latest
    container: mukn/glow:devel
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: ./scripts/ci.ss local-all
