name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  test_job:
    runs-on: ubuntu-latest
    container: mukn/glow:devel
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - run: ./scripts/ci.ss before-test
      - run: ./scripts/ci.ss test
      - run: ./scripts/ci.ss after-test
